### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by joepio** [joepio/pauseai#26]
No need for a big elastic thing. Maybe use [`tinysearch`](https://github.com/tinysearch/tinysearch), which compiles everything as a small module statically.

**Comment by Wituareard** [comment]
[Pagefind ](https://pagefind.app/) looks promising.

- parses the html output so it doesn't need an index file
- doesn't need full words
- prebuilt UI

Maybe I'll take a closer look at it in the next few days.
