### ISSUE TITLE
Mark external links

### ISSUE THREAD

**Issue by Wituareard** [joepio/pauseai#28]
When browsing the website, I found it frustrating that I didn't know which links I could use to navigate around the website and which ones would take me elsewhere. Maybe it would be a good idea to mark external links.

I will submit a PR that potentially solves the issue by appending an icon, but I don't know if that's the best solution and if it should be implemented differently, so I also opened this issue.

**Comment by joepio** [comment]
I share your frustration, thanks for making this issue!

I think a possible solution is to provide a custom link renderer for MDXSvelte. Are you already working on this?

**Comment by Wituareard** [comment]
I implemented a solution using plain CSS, see the PR above.

**Comment by joepio** [comment]
I just implemented it with a custom component, but I prefer your approach! Reverted my own thing, kept yours. Thanks!

**Comment by joepio** [comment]
Hmm wait... this leads to an unknown icon thing... I think maybe we do need my approach? What do you think?

![Uploading Screenshot 2024-01-02 at 23.21.35.png…]()

**Comment by joepio** [comment]
Approach doesn't matter that much anyways. I've used my changes instead of yours (sorry!) and it now renders correctly here.

**Comment by Wituareard** [comment]
No problem, but maybe the icon should be smaller and also be used in the footer?

**Comment by joepio** [comment]
Hmm good points. I'll probably work on that soon!
