### ISSUE TITLE
Quotes page about AIXR

### ISSUE THREAD

**Issue by Pato-desu** [joepio/pauseai#80]
Of important people from Turing to António Guterres from the UN

If we get slowing down or regulatory support quotes even better

**Comment by Pato-desu** [comment]
https://moratorium.ai has a bunch

**Comment by Wituareard** [comment]
Something like that has been introduced with #20, but there are some technical problems with the current version, see #79 and #81

**Comment by Wituareard** [comment]
You could still suggest specific quotes to add here, and the website seems to be a useful resource.
