### ISSUE TITLE
Links to markdown files don't work in dev preview

### ISSUE THREAD

**Issue by Wituareard** [joepio/pauseai#81]
Something in [a82e268](https://github.com/joepio/pauseai/commit/a82e2689028fd072d18330b2193488815d311047) broke the vite dev server, so that I can't navigate between markdown files in the dev preview anymore. Links to other pages work fine.

**Comment by Wituareard** [comment]
The build might also be affected, since the current version isn't deployed because of the malformed link I fixed in #79.

**Comment by Wituareard** [comment]
The changes in app.d.ts looked the most like they could have messed with markdown rendering. Reverting them didn't fix it for me, but maybe I made a mistake.

**Comment by joepio** [comment]
Hmm concerning, I'll check it out

**Comment by Wituareard** [comment]
Because the latest commit fixed the link, now it also affects the deployed site.

**Comment by Wituareard** [comment]
Found the problem

**Comment by joepio** [comment]
The issue was a page with a broken link, my bad. Is fixed now.
